# Tensors

Tensors are a specialized data structure that are very similar to arrays and matrices.  
텐서는 arrays 및 matrices와 매우 유사한 전문 데이터 구조  
내부에 데이터를 배열 형태로 저장   
배열을 잘 처리하기 위한 하나의 클래스 구조임  
배치로 나누고, 자동미분 적용을 위한 처리 등 멤버함수가 구현되어있음  

In PyTorch, we use tensors / to encode the inputs and outputs of a model, as well as the model’s parameters.  
PyTorch에서는 텐서를 사용하여 / 모델의 입력과 출력 : 모델의 파라미터를 인코딩  

Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators.   
텐서는 GPU나 다른 하드웨어 가속기에서 실행할 수 있다는 점을 제외하고는 NumPy의 nandarray와 유사  

In fact, tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data (see Bridge with NumPy).   
실제로 텐서와 NumPy 어레이는 동일한 기본 메모리를 공유할 수 있으므로 데이터를 복사할 필요가 없음(Bridge with NumPy 참조)

Tensors are also optimized for automatic differentiation (we’ll see more about that later in the Autograd section).  
또한 텐서는 자동 차별화에 최적화되어 있음(이에 대한 자세한 내용은 나중에 Autograd 섹션에서 확인)  

If you’re familiar with ndarrays, you’ll be right at home with the Tensor API. If not, follow along!  
ndarray에 익숙하다면 Tensor API를 집에서 바로 사용할 수 있음

In [3]:
import torch 
import numpy as np 

### Initializing a Tensor
텐서 초기화  

ensors can be initialized in various ways. Take a look at the following examples:  
: 텐서는 다양한 방법으로 초기화할 수 있음  

##### **Directly from data**  

Tensors can be created directly from data.   
텐서는 데이터에서 직접 만들 수 있음

The data type is automatically inferred.  
데이터 유형은 자동으로 추론

In [4]:
data = [[1, 2],[3, 4]] 
x_data = torch.tensor(data) 

##### **From a NumPy array**

Tensors can be created from NumPy arrays (and vice versa - see `bridge-to-np-label`)   
텐서는 NumPy 어레이에서 생성할 수 있음(그 반대의 경우도 마찬가지)


In [5]:
np_array = np.array(data) 
x_np = torch.from_numpy(np_array) 

##### **From another tensor:**

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.  
새로운 텐서는 명시적으로 무시되지 않는 한 인수 텐서의 속성(형상, 데이터 유형)을 유지  



In [6]:
x_ones = torch.ones_like(x_data) # retains유지하다 the properties of x_data 
print(f"Ones Tensor: \n {x_ones} \n") 

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data 
print(f"Random Tensor: \n {x_rand} \n") 

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8398, 0.4272],
        [0.0675, 0.6215]]) 



##### **With random or constant values:**

``shape`` is a tuple of tensor dimensions.   
shape 는 텐서 차원의 튜플  

In the functions below, it determines the dimensionality of the output tensor.  
아래 함수에서 출력 텐서의 치수를 결정  

In [7]:
shape = (2,3,) # 마지막 ,는 있어도 되고 없어도 됨
rand_tensor = torch.rand(shape) 
ones_tensor = torch.ones(shape) 
zeros_tensor = torch.zeros(shape)  

print(f"Random Tensor: \n {rand_tensor} \n") 
print(f"Ones Tensor: \n {ones_tensor} \n") 
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.8822, 0.3106, 0.7585],
        [0.3490, 0.9206, 0.9720]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


---

### Attributes of a Tensor
Tensor attributes describe their shape, datatype, and the device on which they are stored.  
텐서 속성은 모양, 데이터 유형 및 저장된 장치를 설명

In [11]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


---

### Operations on Tensors 텐서에 대한 연산

Over 100 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing,
indexing, slicing), sampling and more are
comprehensively described [here](https://pytorch.org/docs/stable/torch.html)_.  
산술, 선형 대수, 행렬 조작(트랜스포징, 인덱싱, 슬라이싱), 샘플링 등을 포함한 100개 이상의 텐서 연산이 링크에 포괄적으로 설명되어 있음

Each of these operations can be run on the GPU (at typically higher speeds than on a CPU).  
이러한 각 작업은 GPU(일반적으로 CPU보다 더 빠른 속도)에서 실행될 수 있음  

If you’re using Colab, allocate a GPU by going to Runtime > Change runtime type > GPU.  
Colab을 사용하는 경우 Runtime > Change runtime type > GPU로 이동하여 GPU를 할당

By default, tensors are created on the CPU.  
기본적으로 CPU에 텐서가 생성됨  

We need to explicitly move tensors to the GPU using .to method (after checking for GPU availability).   
우리는 명시적으로 텐서를 GPU로 이동시켜야 함 using .to method (GPU 가용성 확인 후)

Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!  
장치 전반에 걸쳐 대형 텐서를 복사하는 것은 시간과 메모리 측면에서 비용이 많이 들 수 있다는 것을 명심

In [7]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

Try out some of the operations작업 from the list.   

If you’re familiar with the NumPy API, you’ll find the Tensor API a breeze to use.  
NumPy API에 대해 잘 알고 있다면 Tensor API를 쉽게 사용할 수 있음  

##### Standard numpy-like indexing and slicing:
표준 Numpy-like 인덱싱 및 슬라이싱:

In [8]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


##### Joining tensors   

You can use torch.cat to concatenate a sequence of tensors along a given dimension.  
주어진 차원을 따라 일련의 텐서를 연결   

See also ``torch.stack``, another tensor joining operator that is subtly different from `torch.cat`.  
subtly 미묘한

In [12]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[0.4890, 0.4984, 0.3227, 0.7768, 0.4890, 0.4984, 0.3227, 0.7768, 0.4890,
         0.4984, 0.3227, 0.7768],
        [0.6828, 0.2250, 0.8209, 0.7472, 0.6828, 0.2250, 0.8209, 0.7472, 0.6828,
         0.2250, 0.8209, 0.7472],
        [0.9573, 0.8825, 0.5057, 0.1998, 0.9573, 0.8825, 0.5057, 0.1998, 0.9573,
         0.8825, 0.5057, 0.1998]])


In [14]:
t2 = torch.stack([tensor, tensor, tensor], dim=1)
print(t2)

tensor([[[0.4890, 0.4984, 0.3227, 0.7768],
         [0.4890, 0.4984, 0.3227, 0.7768],
         [0.4890, 0.4984, 0.3227, 0.7768]],

        [[0.6828, 0.2250, 0.8209, 0.7472],
         [0.6828, 0.2250, 0.8209, 0.7472],
         [0.6828, 0.2250, 0.8209, 0.7472]],

        [[0.9573, 0.8825, 0.5057, 0.1998],
         [0.9573, 0.8825, 0.5057, 0.1998],
         [0.9573, 0.8825, 0.5057, 0.1998]]])


##### Arithmetic operations 산술연산

In [10]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

##### Single-element tensors 

If you have a one-element tensor, for example by aggregating all values of a tensor into one value,   
예를 들어, 텐서의 모든 값을 하나의 값으로 집계하여 단일 요소 텐서를 갖는 경우,  

you can convert it to a Python numerical value using item():  
다음을 사용하여 그것을 파이썬 수치로 변환할 수 있음

In [11]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


##### In-place operations 

Operations that store the result into the operand are called in-place.  
결과를 피연산자에 저장하는 Operations를 in-place라고 함  

They are denoted by a _ suffix.   
For example: x.copy_(y), x.t_(), will change x.  

In [12]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


##### NOTE

In-place operations save some memory,   
In-place 연산은 일부 메모리를 절약하지만,  

but can be problematic when computing derivatives because of an immediate loss of history.  
즉각적인 이력 손실로 인해 도함수를 계산할 때 문제가 될 수 있음  

Hence, their use is discouraged.
따라서 사용이 권장되지 않음

---

## Bridge with NumPy

Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.  
CPU 및 NumPy 어레이의 텐서는 기본 메모리 위치를 공유할 수 있으며, 하나를 변경하면 다른 하나가 변경됨

### Tensor to NumPy array

In [13]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array.

In [14]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### NumPy array to Tensor

In [15]:
n = np.ones(5)
t = torch.from_numpy(n)

Changes in the NumPy array reflects in the tensor  
넘파이 배열에서 변경하면 텐서에 반영됨

In [16]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
