# Tensors

텐서는 어레이 및 매트릭스와 매우 유사한 전문 데이터 구조
PyTorch에서는 텐서를 사용하여 모델의 입력과 출력 및 모델의 파라미터를 인코딩

텐서는 GPU나 다른 하드웨어 가속기에서 실행할 수 있다는 점을 제외하고는 NumPy의 nandarray와 유사
실제로 텐서와 NumPy 어레이는 동일한 기본 메모리를 공유할 수 있으므로 데이터를 복사할 필요가 없음(Bridge with NumPy 참조)
또한 텐서는 자동 차별화에 최적화되어 있음(이에 대한 자세한 내용은 나중에 Autograd 섹션에서 확인) 
ndarray에 익숙하다면 Tensor API를 사용하면 집에서 바로 사용할 수 있음

In [3]:
import torch 
import numpy as np 

텐서 초기화
: 텐서는 다양한 방법으로 초기화할 수 있음

In [4]:
# 데이터에서 직접

# 텐서는 데이터에서 직접 만들 수 있음
# 데이터 유형은 자동으로 추론

data = [[1, 2],[3, 4]] 
x_data = torch.tensor(data) 

In [6]:
# NumPy 배열에서

# 텐서는 NumPy 어레이에서 생성할 수 있음(그 반대의 경우도 마찬가지)

np_array = np.array(data) 
x_np = torch.from_numpy(np_array) 

In [10]:
# 또 다른 텐서로부터:
# 새로운 텐서는 명시적으로 무시되지 않는 한 인수 텐서의 속성(형상, 데이터 유형)을 유지

x_ones = torch.ones_like(x_data) # retains the properties of x_data 
print(f"Ones Tensor: \n {x_ones} \n") 

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data 
print(f"Random Tensor: \n {x_rand} \n") 

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.9338, 0.6942],
        [0.3190, 0.6513]]) 



In [11]:
# 랜덤 또는 상수 값을 사용하는 경우:
# shape 는 텐서 차원의 튜플
# 아래 함수에서 출력 텐서의 치수를 결정

shape = (2,3,) 
rand_tensor = torch.rand(shape) 
ones_tensor = torch.ones(shape) 
zeros_tensor = torch.zeros(shape)  

print(f"Random Tensor: \n {rand_tensor} \n") 
print(f"Ones Tensor: \n {ones_tensor} \n") 
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.3505, 0.2417, 0.2462],
        [0.2805, 0.0076, 0.2079]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


Attributes of a Tensor
Tensor attributes describe their shape, datatype, and the device on which they are stored.
텐서의 속성
텐서 속성은 모양, 데이터 유형 및 저장된 장치를 설명

In [12]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


Operations on Tensors 텐서에 대한 연산

산술, 선형 대수, 행렬 조작(트랜스포징, 인덱싱, 슬라이싱), 샘플링 등을 포함한 100개 이상의 텐서 연산이 여기에 포괄적으로 설명되어 있음

이러한 각 작업은 GPU(일반적으로 CPU보다 더 빠른 속도)에서 실행될 수 있음 
Colab을 사용하는 경우 Runtime > Change runtime type > GPU로 이동하여 GPU를 할당

기본적으로 CPU에는 텐서가 생성됨 
우리는 명시적으로 텐서를 GPU로 이동시켜야 함 using .to method (GPU 가용성 확인 후)
장치 전반에 걸쳐 대형 텐서를 복사하는 것은 시간과 메모리 측면에서 비용이 많이 들 수 있다는 것을 명심

In [13]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

Try out some of the operations from the list. If you’re familiar with the NumPy API, you’ll find the Tensor API a breeze to use.
목록에서 몇 가지 작업을 시도해 보십시오. NumPy API에 대해 잘 알고 있다면 Tensor API를 쉽게 사용할 수 있습니다.

Standard numpy-like indexing and slicing:
표준 Numpy-like 인덱싱 및 슬라이싱:

In [14]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


Joining tensors 
You can use torch.cat to concatenate a sequence of tensors along a given dimension.
주어진 차원을 따라 일련의 텐서를 연결 
See also torch.stack, another tensor joining operator that is subtly different from torch.cat.

In [15]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


Arithmetic operations 산술연산

In [16]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

Single-element tensors 

If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using item():
예를 들어, 텐서의 모든 값을 하나의 값으로 집계하여 단일 요소 텐서를 갖는 경우, 다음을 사용하여 그것을 파이썬 수치로 변환할 수 있음

In [17]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In-place operations 
Operations that store the result into the operand are called in-place. 
결과를 피연산자에 저장하는 Operations를 in-place라고 함

They are denoted by a _ suffix. 
For example: x.copy_(y), x.t_(), will change x.

In [18]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


##### NOTE

In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. 
in-place 연산은 일부 메모리를 절약하지만, 즉각적인 이력 손실로 인해 도함수를 계산할 때 문제가 될 수 있음

Hence, their use is discouraged.
따라서 사용이 권장되지 않음

## Bridge with NumPy

Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.
CPU 및 NumPy 어레이의 텐서는 기본 메모리 위치를 공유할 수 있으며, 하나를 변경하면 다른 하나가 변경됨

### Tensor to NumPy array

In [19]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array.

In [20]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### NumPy array to Tensor

In [21]:
n = np.ones(5)
t = torch.from_numpy(n)

Changes in the NumPy array reflects in the tensor
넘파이 배열에서 변경하면 텐서에 반영됨

In [23]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
